
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 70
#define YY_END_OF_BUFFER 71
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[546] =
    {   0,
        0,    0,   71,   69,   66,   70,   65,   21,   18,   17,
       65,   22,   64,   63,   23,    2,   24,   19,   20,   63,
       53,   54,   55,   56,   63,   57,   58,    3,   16,    4,
       66,   65,    0,   64,    5,   15,   68,   68,   68,   68,
       68,   68,   68,   68,   68,   68,   68,   68,   68,   68,
       68,   68,   68,   68,   68,   68,    1,   68,   68,   68,
       68,   68,   68,   68,   68,   68,   68,   68,   68,   67,
       68,   68,   68,   68,   68,   68,   68,   68,   65,   65,
       65,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   68,   68,
       68,   68,   68,   68,   68,   68,   68,   62,   68,   68,
       68,   68,   68,   68,   68,   68,   68,   68,   68,   68,
       46,   68,   68,   68,   68,   68,   48,   68,   68,   68,
       68,   68,   68,   68,   68,   68,   68,   68,   68,   68,
       68,   68,   68,   68,   68,   68,   68,   68,   68,   68,
       68,   68,   68,   68,   68,   65,   65,   65,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   65,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   68,   68,
       68,   68,   68,   68,   68,   68,   65,   68,   68,   68,
       68,   68,   68,   68,   68,   68,   68,   68,   68,   68,
       68,   68,   68,   68,   68,   68,   68,   68,   62,   68,
       68,   68,   68,   68,   68,   68,   68,   68,   68,   68,
       68,   68,   68,   68,   68,   68,   65,   65,    8,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   68,   68,   68,

       68,   68,   68,   68,   68,   68,   68,   68,   68,   68,
       68,   68,   11,   68,   68,   49,    0,   68,   59,   68,
       68,   68,   65,   35,   68,   68,   68,   68,   68,   68,
       68,   68,   68,   60,   68,   68,   68,   68,   65,   65,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   68,   68,   68,   68,   68,   68,   68,   68,
        0,    0,    0,    0,    0,   68,   52,   68,   61,    0,
       68,   68,   68,   50,   68,   68,   68,   68,   10,   68,
       65,    9,    0,    0,    0,    0,    0,    0,    0,    0,

       68,   68,   68,   12,    0,   68,   68,    0,    0,    0,
        0,    0,    0,   68,   51,   36,   13,   68,   14,   68,
       45,   47,   68,    7,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   37,   68,    0,    0,    0,
        0,    0,    0,   40,    0,    0,    0,    0,    0,    0,
       68,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   68,    0,    0,    0,    0,   26,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       68,    0,    0,   30,   32,   42,    0,    0,    0,    0,
        0,    0,   25,    0,    0,    0,   68,    0,    0,    0,

        0,    0,    0,   29,   31,   41,    0,    0,   68,    0,
        0,   44,    0,    0,    0,    0,    0,    6,   39,    0,
        0,    0,    0,   43,    0,   28,    0,   38,    0,    0,
        0,   27,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   34,    0,   33,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    1,    6,    7,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,    1,   18,   19,   20,
       18,   18,   18,   18,   18,   18,   18,   21,   22,    1,
       23,    1,   24,   25,   26,   27,   28,   29,   30,   28,
       31,   28,   32,   28,   33,   34,   35,   36,   37,   38,
       28,   39,   40,   41,   42,   28,   28,   43,   28,   44,
       45,   46,   47,   48,   49,    1,   50,   51,   52,   53,

       54,   55,   56,   57,   58,   28,   59,   60,   61,   62,
       63,   64,   65,   66,   67,   68,   69,   28,   28,   70,
       71,   72,   73,   74,   75,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[76] =
    {   0,
        1,    1,    1,    1,    2,    1,    1,    1,    1,    2,
        1,    1,    3,    1,    2,    1,    2,    2,    2,    2,
        2,    2,    1,    2,    1,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    1,    2,    1,    1,    1,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    1,    1,    1
    } ;

static const flex_int16_t yy_base[550] =
    {   0,
        0,    0,  981,  982,   74,  982,  934,  982,  982,  982,
      982,  982,   61,  933,  982,  104,  982,  982,  982,   31,
      932,  931,  930,   36,   37,  929,  928,  982,  982,  982,
       82,  927,  151,   69,  982,  982,    0,   89,   72,  959,
       97,  166,   78,  183,   79,  103,   83,  184,  186,  185,
      187,  193,  209,  203,  211,  195,  982,  212,  216,  213,
      214,  222,  219,  215,  220,  226,  223,  225,  224,  227,
      218,  241,  245,  247,  263,  242,  249,  243,   52,   53,
       48,  911,  916,  915,   36,  918,  904,  916,  915,  895,
      894,  901,   56,  904,  902,   68,  895,  900,  903,  896,

      901,  885,  899,  193,  902,   43,  901,  900,  880,  879,
      886,  252,  889,  887,  191,  880,  885,  888,  265,  232,
      290,  237,  298,  301,  302,  303,  305,  366,  310,  311,
      314,  312,  309,  313,  319,  322,  323,  328,  325,  338,
      928,  326,  331,  329,  318,  344,  334,  321,  332,  330,
      336,  388,  341,  345,  340,  350,  339,  395,  346,  396,
      398,  347,  401,  402,  403,  404,  409,  406,  407,  408,
      410,  412,  411,  414,  415,  282,  287,   49,  876,  871,
      878,  870,  886,  874,  866,  869,  871,  885,  372,  872,
      871,  865,  871,  857,  871,  857,  855,  858,  853,  856,

      859,  851,  867,  852,  854,   54,  846,  849,  851,  375,
      853,  852,  846,  852,  838,  852,  838,  836,  418,  419,
      421,  424,  423,  422,  426,  427,  486,  429,  434,  431,
      430,  435,  437,  438,  440,  442,  461,  451,  458,  450,
      433,  457,  455,  463,  475,  481,  500,  502,  835,  503,
      504,  506,  507,  510,  511,  509,  513,  512,  516,  517,
      518,  520,  521,  522,  523,  524,  492,   73,  856,  844,
      850,  831,  840,  836,  846,  831,  843,  837,  840,  830,
      822,  831,  838,  830,  836,  817,  826,  822,  832,  817,
      829,  823,  826,  816,  808,  817,  824,  526,  527,  530,

      533,  535,  534,  541,  528,  542,  543,  536,  547,  532,
      537,  538,  860,  551,  544,  859,  549,  556,  858,  558,
      546,  559,  799,  562,  585,  560,  566,  591,  567,  599,
      601,  605,  602,  856,  606,  608,  611,  607,  576,  577,
      818,  817,  806,  815,  814,  810,  812,  795,  810,  809,
      798,  807,  806,  795,  804,  803,  799,  801,  784,  799,
      798,  787,  612,  616,  614,  615,  617,  618,  619,  625,
      783,  783,  786,  793,  280,  621,  829,  626,    0,  794,
      624,  627,  629,  827,  631,  632,  633,  634,  826,  635,
      605,  792,  774,  786,  772,  771,  770,  782,  768,  767,

      637,  641,  642,  816,  633,  636,  643,  776,  758,  759,
      757,  773,  769,  649,  809,  982,  808,  655,  807,  656,
      806,  805,  657,  771,  754,  753,  752,  751,  750,  749,
      747,  747,  750,  757,  632,  793,  640,  736,  743,  735,
      745,  385,  750,  787,  747,  729,  730,  728,  744,  740,
      658,  732,  738,  687,  716,  736,  729,  730,  718,  725,
      717,  727,  640,  732,  663,  728,  715,  705,  704,  982,
      703,  727,  725,  714,  720,  693,  698,  718,  711,  712,
      677,  707,  718,  982,  982,  982,  701,  706,  711,  698,
      688,  687,  982,  686,  702,  698,  659,  680,  679,  671,

      687,  682,  693,  982,  982,  982,  676,  681,  683,  665,
      685,  982,  675,  669,  668,  660,  676,  720,  982,  657,
      675,  655,  675,  982,  665,  982,  659,  982,  649,  666,
      671,  982,  654,  652,  665,  657,  377,  290,  299,  271,
       53,  982,   18,  982,  982,  749,  751,  753,  756
    } ;

static const flex_int16_t yy_def[550] =
    {   0,
      545,    1,  545,  545,  545,  545,  546,  545,  545,  545,
      545,  545,  546,  546,  545,  545,  545,  545,  545,  546,
      546,  546,  546,  546,  546,  546,  546,  545,  545,  545,
      545,  546,  545,  546,  545,  545,  547,  548,  548,  548,
      548,  548,  548,  548,  548,  548,  548,  548,  548,  548,
      548,  548,  548,  548,  548,  548,  545,  548,  548,  548,
      548,  548,  548,  548,  548,  548,  548,  548,  548,  548,
      548,  548,  548,  548,  548,  548,  548,  548,  546,  546,
      546,  545,  545,  545,  545,  545,  545,  545,  545,  545,
      545,  545,  545,  545,  545,  545,  545,  545,  545,  545,

      545,  545,  545,  545,  545,  545,  545,  545,  545,  545,
      545,  545,  545,  545,  545,  545,  545,  545,  548,  548,
      548,  548,  548,  548,  548,  548,  548,  549,  548,  548,
      548,  548,  548,  548,  548,  548,  548,  548,  548,  548,
      548,  548,  548,  548,  548,  548,  548,  548,  548,  548,
      548,  548,  548,  548,  548,  548,  548,  548,  548,  548,
      548,  548,  548,  548,  548,  548,  548,  548,  548,  548,
      548,  548,  548,  548,  548,  546,  546,  546,  545,  545,
      545,  545,  545,  545,  545,  545,  545,  546,  545,  545,
      545,  545,  545,  545,  545,  545,  545,  545,  545,  545,

      545,  545,  545,  545,  545,  545,  545,  545,  545,  545,
      545,  545,  545,  545,  545,  545,  545,  545,  548,  548,
      548,  548,  548,  548,  548,  548,  549,  548,  548,  548,
      548,  548,  548,  548,  548,  548,  548,  548,  548,  548,
      548,  548,  548,  548,  548,  548,  548,  548,  227,  548,
      548,  548,  548,  548,  548,  548,  548,  548,  548,  548,
      548,  548,  548,  548,  548,  548,  546,  546,  546,  545,
      545,  545,  545,  545,  545,  545,  545,  545,  545,  545,
      545,  545,  545,  545,  545,  545,  545,  545,  545,  545,
      545,  545,  545,  545,  545,  545,  545,  548,  548,  548,

      548,  548,  548,  548,  548,  548,  548,  548,  548,  548,
      548,  548,  548,  548,  548,  548,  545,  548,  548,  548,
      548,  548,  227,  548,  548,  548,  548,  548,  548,  548,
      548,  548,  548,  548,  548,  548,  548,  548,  546,  546,
      545,  545,  545,  545,  545,  545,  545,  545,  545,  545,
      545,  545,  545,  545,  545,  545,  545,  545,  545,  545,
      545,  545,  548,  548,  548,  548,  548,  548,  548,  548,
      545,  545,  545,  545,  545,  548,  548,  548,  227,  545,
      548,  548,  548,  548,  548,  548,  548,  548,  548,  548,
      546,  546,  545,  545,  545,  545,  545,  545,  545,  545,

      548,  548,  548,  548,  545,  548,  548,  545,  545,  545,
      545,  545,  545,  548,  548,  545,  548,  548,  548,  548,
      548,  548,  548,  546,  545,  545,  545,  545,  545,  545,
      545,  545,  545,  545,  545,  548,  548,  545,  545,  545,
      545,  545,  545,  548,  545,  545,  545,  545,  545,  545,
      548,  545,  545,  545,  545,  545,  545,  545,  545,  545,
      545,  545,  545,  545,  548,  545,  545,  545,  545,  545,
      545,  545,  545,  545,  545,  545,  545,  545,  545,  545,
      548,  545,  545,  545,  545,  545,  545,  545,  545,  545,
      545,  545,  545,  545,  545,  545,  548,  545,  545,  545,

      545,  545,  545,  545,  545,  545,  545,  545,  548,  545,
      545,  545,  545,  545,  545,  545,  545,  548,  545,  545,
      545,  545,  545,  545,  545,  545,  545,  545,  545,  545,
      545,  545,  545,  545,  545,  545,  545,  545,  545,  545,
      545,  545,  545,  545,    0,  545,  545,  545,  545
    } ;

static const flex_int16_t yy_nxt[1058] =
    {   0,
        4,    5,    6,    5,    7,    8,    9,    4,   10,    7,
       11,   11,    4,   12,    7,   12,    7,   13,   13,   13,
        7,    7,   12,    7,    8,   14,   14,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   14,   14,   14,
       14,   14,   14,   14,   15,   16,   17,   18,   19,   20,
       21,   22,   14,   14,   14,   14,   23,   14,   14,   24,
       14,   14,   14,   25,   14,   26,   14,   27,   14,   14,
       14,   14,   28,   29,   30,   31,   33,   31,   34,   34,
       34,   33,   33,   31,   37,   31,   34,   34,   34,   80,
       37,   37,  544,   33,   33,   37,   79,   33,   33,  182,

      269,   37,   81,  183,  206,  207,   33,   35,  188,   37,
      178,   36,  190,  188,   33,   37,   37,  194,   33,  176,
      177,  188,  191,  543,  195,  120,  340,  124,  126,   38,
       39,   40,   41,   42,   43,   44,   45,   46,   47,   48,
       49,   50,   51,   52,   53,   54,   55,   56,  119,   57,
      121,  128,  127,   58,   59,   60,   61,   62,   63,   64,
       65,   66,   67,   68,   69,   70,   71,   72,   40,   73,
       74,   75,   76,   77,   40,   78,   82,   83,   37,   84,
       85,   86,   87,   88,   89,   90,   91,   92,   93,   94,
       95,   96,   97,   98,   99,   37,   37,   37,   37,   37,

      100,  101,  102,  103,  104,   37,  105,   37,  106,  107,
      108,  109,  110,  111,  112,   37,  113,  114,  115,  116,
      117,   37,  118,   37,   37,   37,   37,   37,   37,  122,
       37,   37,   37,  123,   37,   37,   37,   37,   37,   37,
      215,  130,  128,  132,   37,  125,  129,  216,  137,   37,
      133,  131,  128,   37,   37,   37,  202,   37,  134,   37,
      203,   37,  204,  144,  153,  135,  136,  145,  128,  140,
      141,  138,  159,  142,  160,   37,  146,   37,  161,  154,
      139,  143,  147,  148,  152,  149,  155,  156,  157,  150,
      162,  151,  128,  158,  165,  128,  175,  163,  128,  220,

      167,  166,   37,  222,  168,  174,  128,  164,  211,  188,
       37,  169,  170,   37,   37,   37,  171,   37,  212,  172,
      173,   37,   37,   37,   37,   37,   37,   33,  219,  412,
       37,   37,   33,   37,   37,   37,  413,   37,   37,  267,
       37,   37,   37,   37,   37,  542,   37,  128,   37,  221,
       37,   37,   37,   37,  268,  541,   37,   37,   37,   37,
      540,  223,   37,  228,  230,  226,  225,  229,  128,  224,
       32,  128,  231,  243,  128,   32,  238,  240,   37,  128,
       32,  128,   32,   32,   32,   32,   32,   32,  232,   32,
      233,  234,  235,  236,  128,  241,  239,  242,  244,  128,

       37,  246,  247,  248,  249,  237,  250,   37,   37,  252,
       37,   33,  257,   37,   37,   37,   37,  128,   37,   37,
       37,   37,   37,   37,   37,  278,   37,   37,  292,  279,
       37,   37,  293,   37,   37,   37,   37,  245,   37,   37,
      539,   37,   37,   37,  456,   37,   37,   37,  251,   37,
       37,  255,   37,  457,   37,  256,  253,  254,  128,  128,
      259,  260,   37,   37,  258,  263,  128,   37,  128,   37,
       37,  128,  261,   37,  298,   37,  128,  303,  264,  262,
      265,  300,  266,  301,  304,  305,  128,   37,  299,  302,
       32,  306,  308,   37,  309,   32,  310,  307,   37,  311,

       32,  315,   32,   32,   32,   32,   32,   32,  312,   32,
      128,  313,   37,  316,   37,   37,   37,  314,   37,   37,
      318,   37,   37,   37,   37,   37,  319,  317,   37,   37,
       37,   33,   37,   37,   37,   37,   37,   33,   37,   37,
       37,  320,   37,  339,   37,   37,   37,   37,   37,   37,
       37,  322,  128,   37,   37,   37,   37,  326,   37,   37,
      329,  321,  330,   37,  324,  327,  328,  331,   37,  325,
       37,   37,   37,  128,   37,  128,  128,  333,   37,   37,
      338,  337,  128,  332,  128,  334,  364,  335,  336,  363,
      128,  128,  128,  365,  367,  366,  128,   37,  368,  377,

      128,  371,  372,   37,  370,  369,  380,  128,  373,  374,
      378,   37,  381,   37,   37,  376,  375,   37,   37,   37,
       37,   33,   33,   37,   37,  382,   37,   37,   37,   37,
       37,   37,  383,   37,  128,  391,   37,   37,   37,   37,
      128,   37,  392,   37,   37,   37,   37,   37,   37,   37,
       33,  128,   37,   37,   37,   37,  387,  128,  424,  384,
      385,   37,  386,  388,  389,  128,  390,   37,   37,   37,
       37,   37,  406,  128,  401,   37,  402,  403,  407,  415,
      417,  449,  404,  414,  419,  431,  432,  421,  450,   37,
      405,  418,  433,  434,  420,   37,  436,  423,  128,  478,

      435,  422,  128,  128,  437,  468,  469,  451,  479,  465,
      128,  491,  492,  538,  537,  536,  128,  444,  128,  535,
      534,  533,  481,  532,  531,  509,  497,  530,  529,  528,
      527,  526,   37,  525,  524,  523,  522,  521,  520,  519,
      517,  516,  515,  514,  513,  512,  511,  510,  508,  518,
       32,  507,   32,   37,   37,   40,   40,  227,  227,  227,
      506,  505,  504,  503,  502,  501,  500,  499,  498,  496,
      495,  494,  493,  490,  489,  488,  487,  486,  485,  484,
      483,  482,  480,  477,  476,  475,  474,  473,  472,  471,
      470,  467,  466,  464,  463,  462,  461,  460,  459,   37,

      458,  455,  454,  453,  452,   37,  448,  447,  446,  445,
      188,  188,  188,  188,  188,  188,   33,   37,   37,   37,
       37,   37,  443,  442,  441,  440,  439,  438,   37,  430,
      429,  188,  428,  427,  426,  188,  425,   33,   37,   37,
      416,   37,  411,  410,  409,  408,  400,  188,  188,  399,
      188,  398,  188,  188,  397,  188,  188,  396,  188,  188,
      395,  188,  394,  188,  188,  393,  188,  188,   37,  379,
       37,   37,   37,  188,  362,  361,  360,  359,  358,  357,
      356,  188,  355,  354,  353,  188,  352,  188,  351,  350,
      349,  348,  347,  346,  345,  188,  344,  343,  342,  188,

      341,   33,  323,  297,  296,  295,  188,  294,  188,  188,
      188,  291,  290,  289,  288,  188,  188,  287,  286,  188,
      285,  284,  283,  282,  281,  188,  280,  188,  188,  188,
       33,  277,  276,  275,  274,  188,  273,  272,  271,  270,
       37,  218,  188,  217,  214,  213,  210,  188,  188,  209,
      208,  205,  201,  200,  199,  198,  197,  188,  196,  193,
      192,  189,  188,  188,  187,  186,  185,  184,  181,  180,
      179,   37,   33,   33,   33,   33,   33,   33,   33,   33,
      545,    3,  545,  545,  545,  545,  545,  545,  545,  545,
      545,  545,  545,  545,  545,  545,  545,  545,  545,  545,

      545,  545,  545,  545,  545,  545,  545,  545,  545,  545,
      545,  545,  545,  545,  545,  545,  545,  545,  545,  545,
      545,  545,  545,  545,  545,  545,  545,  545,  545,  545,
      545,  545,  545,  545,  545,  545,  545,  545,  545,  545,
      545,  545,  545,  545,  545,  545,  545,  545,  545,  545,
      545,  545,  545,  545,  545,  545,  545
    } ;

static const flex_int16_t yy_chk[1058] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    5,   20,    5,   13,   13,
       13,   24,   25,   31,   39,   31,   34,   34,   34,   24,
       43,   45,  543,   81,  178,   47,   20,   79,   80,   85,

      178,   38,   25,   85,  106,  106,   13,   16,  206,   41,
       81,   16,   93,   93,   34,   46,   16,   96,  268,   79,
       80,  206,   93,  541,   96,   39,  268,   43,   45,   16,
       16,   16,   16,   16,   16,   16,   16,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   16,   38,   16,
       41,   47,   46,   16,   16,   16,   16,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   33,   33,   42,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   44,   48,   50,   49,   51,

       33,   33,   33,   33,   33,   52,   33,   56,   33,   33,
       33,   33,   33,   33,   33,   54,   33,   33,   33,   33,
       33,   53,   33,   55,   58,   60,   61,   64,   59,   42,
       71,   63,   65,   42,   62,   67,   69,   68,   66,   70,
      115,   50,   50,   51,  120,   44,   49,  115,   56,  122,
       52,   50,   48,   72,   76,   78,  104,   73,   53,   74,
      104,   77,  104,   61,   64,   53,   54,   61,   55,   59,
       59,   58,   67,   59,   68,   75,   61,  119,   71,   65,
       58,   60,   62,   62,   63,   62,   65,   66,   66,   62,
       72,   62,   69,   66,   73,   70,   78,   72,   72,  120,

       74,   73,  121,  122,   74,   76,   77,   72,  112,  112,
      123,   74,   75,  124,  125,  126,   75,  127,  112,   75,
       75,  133,  129,  130,  132,  134,  131,  176,  119,  375,
      145,  135,  177,  148,  136,  137,  375,  139,  142,  176,
      138,  144,  150,  143,  149,  540,  147,  123,  151,  121,
      140,  157,  155,  153,  177,  539,  146,  154,  159,  162,
      538,  124,  156,  129,  133,  127,  126,  129,  130,  125,
      128,  131,  135,  148,  132,  128,  142,  145,  128,  150,
      128,  134,  128,  128,  128,  128,  128,  128,  136,  128,
      137,  138,  139,  140,  143,  146,  144,  147,  149,  151,

      152,  153,  154,  155,  156,  140,  157,  158,  160,  159,
      161,  128,  162,  163,  164,  165,  166,  156,  168,  169,
      170,  167,  171,  173,  172,  189,  174,  175,  210,  189,
      219,  220,  210,  221,  224,  223,  222,  152,  225,  226,
      537,  228,  231,  230,  442,  241,  229,  232,  158,  233,
      234,  161,  235,  442,  236,  161,  160,  160,  163,  164,
      167,  168,  240,  238,  165,  172,  166,  243,  220,  242,
      239,  224,  169,  237,  219,  244,  170,  226,  173,  171,
      174,  222,  175,  223,  228,  229,  233,  245,  221,  225,
      227,  230,  232,  246,  234,  227,  235,  231,  227,  236,

      227,  241,  227,  227,  227,  227,  227,  227,  238,  227,
      237,  239,  247,  242,  248,  250,  251,  240,  252,  253,
      244,  256,  254,  255,  258,  257,  245,  243,  259,  260,
      261,  227,  262,  263,  264,  265,  266,  267,  298,  299,
      305,  246,  300,  267,  310,  301,  303,  302,  308,  311,
      312,  248,  250,  304,  306,  307,  315,  253,  321,  309,
      256,  247,  257,  314,  251,  254,  255,  258,  318,  252,
      320,  322,  326,  266,  324,  298,  299,  260,  327,  329,
      265,  264,  301,  259,  302,  261,  303,  262,  263,  300,
      304,  306,  307,  305,  310,  308,  309,  325,  311,  321,

      314,  317,  317,  328,  315,  312,  324,  320,  317,  317,
      322,  330,  326,  331,  333,  318,  317,  332,  335,  338,
      336,  339,  340,  337,  363,  327,  365,  366,  364,  367,
      368,  369,  329,  376,  325,  339,  381,  370,  378,  382,
      328,  383,  340,  385,  386,  387,  388,  390,  406,  401,
      391,  333,  437,  402,  403,  407,  335,  336,  391,  330,
      331,  414,  332,  335,  337,  364,  338,  418,  420,  423,
      451,  497,  369,  381,  363,  465,  365,  366,  370,  378,
      382,  435,  367,  376,  385,  405,  405,  387,  435,  481,
      368,  383,  405,  405,  386,  509,  406,  390,  401,  463,

      405,  388,  402,  403,  407,  454,  454,  437,  463,  451,
      414,  476,  476,  536,  535,  534,  418,  420,  423,  533,
      531,  530,  465,  529,  527,  497,  481,  525,  523,  522,
      521,  520,  518,  517,  516,  515,  514,  513,  511,  510,
      508,  507,  503,  502,  501,  500,  499,  498,  496,  509,
      546,  495,  546,  547,  547,  548,  548,  549,  549,  549,
      494,  492,  491,  490,  489,  488,  487,  483,  482,  480,
      479,  478,  477,  475,  474,  473,  472,  471,  469,  468,
      467,  466,  464,  462,  461,  460,  459,  458,  457,  456,
      455,  453,  452,  450,  449,  448,  447,  446,  445,  444,

      443,  441,  440,  439,  438,  436,  434,  433,  432,  431,
      430,  429,  428,  427,  426,  425,  424,  422,  421,  419,
      417,  415,  413,  412,  411,  410,  409,  408,  404,  400,
      399,  398,  397,  396,  395,  394,  393,  392,  389,  384,
      380,  377,  374,  373,  372,  371,  362,  361,  360,  359,
      358,  357,  356,  355,  354,  353,  352,  351,  350,  349,
      348,  347,  346,  345,  344,  343,  342,  341,  334,  323,
      319,  316,  313,  297,  296,  295,  294,  293,  292,  291,
      290,  289,  288,  287,  286,  285,  284,  283,  282,  281,
      280,  279,  278,  277,  276,  275,  274,  273,  272,  271,

      270,  269,  249,  218,  217,  216,  215,  214,  213,  212,
      211,  209,  208,  207,  205,  204,  203,  202,  201,  200,
      199,  198,  197,  196,  195,  194,  193,  192,  191,  190,
      188,  187,  186,  185,  184,  183,  182,  181,  180,  179,
      141,  118,  117,  116,  114,  113,  111,  110,  109,  108,
      107,  105,  103,  102,  101,  100,   99,   98,   97,   95,
       94,   92,   91,   90,   89,   88,   87,   86,   84,   83,
       82,   40,   32,   27,   26,   23,   22,   21,   14,    7,
        3,  545,  545,  545,  545,  545,  545,  545,  545,  545,
      545,  545,  545,  545,  545,  545,  545,  545,  545,  545,

      545,  545,  545,  545,  545,  545,  545,  545,  545,  545,
      545,  545,  545,  545,  545,  545,  545,  545,  545,  545,
      545,  545,  545,  545,  545,  545,  545,  545,  545,  545,
      545,  545,  545,  545,  545,  545,  545,  545,  545,  545,
      545,  545,  545,  545,  545,  545,  545,  545,  545,  545,
      545,  545,  545,  545,  545,  545,  545
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "latex2html.l"
#line 2 "latex2html.l"


#include "y.tab.h"
#include<stdio.h>
#include<string.h>

int intext = 0, incomment = 0, inmath = 0, inlist=0, inbib=0;
#line 863 "lex.yy.c"
#line 864 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 21 "latex2html.l"

#line 1083 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 546 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 982 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 22 "latex2html.l"
{if(incomment==1); else{printf(" %s \n", yytext);; return(DBLBS);}}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 23 "latex2html.l"
{printf(" %s ", yytext);; return(BACKSL);}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 24 "latex2html.l"
{printf(" %s ", yytext);;return(LCURLYB);}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 25 "latex2html.l"
{printf(" %s ", yytext);;return(RCURLYB);}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 26 "latex2html.l"
{}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 27 "latex2html.l"
{printf(" %s ", yytext);; return(DOCUMENTCLASS);}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 28 "latex2html.l"
{printf(" %s ", yytext);; return(ARTICLE);}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 29 "latex2html.l"
{printf(" %s ", yytext);; return(PROC);}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 30 "latex2html.l"
{printf(" %s ", yytext);; return(LETTER);}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 31 "latex2html.l"
{printf(" %s ", yytext);; return(TITLE);}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 32 "latex2html.l"
{printf(" %s ",yytext);; return(DATE);}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 33 "latex2html.l"
{printf(" %s ",yytext);; return(AUTHOR);}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 34 "latex2html.l"
{ printf(" %s ",yytext);; if(inmath==1) return (LANGLE);else return(WORD);}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 35 "latex2html.l"
{ printf(" %s ",yytext);; if(inmath==1) return (RANGLE);else return(WORD);}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 36 "latex2html.l"
{ if(inmath==1) return (OPERATOR);else{printf(" %s ",yytext);yytext="%";return(WORD);}}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 37 "latex2html.l"
{printf(" %s ", yytext);; return(PIPE);}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 38 "latex2html.l"
{printf(" %s ", yytext);; return(AMPERSAND);}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 39 "latex2html.l"
{printf(" %s ", yytext);; if(inmath == 0) inmath = 1;else inmath= 0; return(DOLLARMATH);}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 40 "latex2html.l"
{printf(" %s ", yytext);; return(SUPERSCRIPT);}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 41 "latex2html.l"
{printf(" %s ", yytext);; return(SUBSCRIPT);}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 42 "latex2html.l"
{printf(" %s ", yytext);; return(WORD);}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 43 "latex2html.l"
{printf(" %s ", yytext);;yylval.arr = strdup(yytext); if(inmath == 1) return(OPERATOR); else return(WORD);}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 44 "latex2html.l"
{printf(" %s ", yytext);; return(LSQRB);}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 45 "latex2html.l"
{printf(" %s ", yytext);; return(RSQRB);}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 46 "latex2html.l"
{printf(" %s ", yytext);; inmath = 1; return(DOLLARMATH);}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 47 "latex2html.l"
{printf(" %s ", yytext);; inmath = 0; return(DOLLARMATH);}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 48 "latex2html.l"
{printf(" %s ", yytext);;inlist++; return(STARTLIST);}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 49 "latex2html.l"
{printf(" %s ", yytext);; inlist--; return(ENDLIST);}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 50 "latex2html.l"
{printf(" %s ", yytext);;inlist++; return(STARTLIST);}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 51 "latex2html.l"
{printf(" %s ", yytext);; inlist--; return(ENDLIST);}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 52 "latex2html.l"
{printf(" %s ", yytext);;inlist++; return(STARTLIST);}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 53 "latex2html.l"
{printf(" %s ", yytext);; inlist--; return(ENDLIST);}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 54 "latex2html.l"
{printf(" %s ", yytext);;inbib=1; return(STARTBIB);}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 55 "latex2html.l"
{printf(" %s ", yytext);;inbib=0; return(ENDBIB);}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 56 "latex2html.l"
{printf(" %s ", yytext);;if(inlist>0) return(ITEM);else return(SWORD);}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 57 "latex2html.l"
{printf(" %s ", yytext);;if(inlist>0) return(ITEM);else return(SWORD);}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 58 "latex2html.l"
{printf(" %s ", yytext);;if(inbib==1) return(BIBITEM);else return(SWORD);}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 59 "latex2html.l"
{printf(" %s ", yytext);; intext = 1;return(LBEGINDOCU);}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 60 "latex2html.l"
{printf(" %s ", yytext);; intext = 0;return(LENDDOCU);}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 61 "latex2html.l"
{printf(" %s ", yytext);; intext = 1;return(SECTION);}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 62 "latex2html.l"
{printf(" %s ", yytext);; intext = 1;return(BEGINTABLE);}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 63 "latex2html.l"
{printf(" %s ", yytext);; intext = 0;return(ENDTABLE);}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 64 "latex2html.l"
{printf(" %s ", yytext);; intext = 1;return(BEGINTABULAR);}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 65 "latex2html.l"
{printf(" %s ", yytext);;return(ENDTABULAR);}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 66 "latex2html.l"
{printf(" %s ", yytext);; return(BOLDFACE);}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 67 "latex2html.l"
{printf(" %s ", yytext);; return(BOLDFACE);}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 68 "latex2html.l"
{printf(" %s ", yytext);; return(ITALICS);}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 69 "latex2html.l"
{printf(" %s ", yytext);; return(ITALICS);}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 70 "latex2html.l"
{printf(" %s ", yytext);; return(ITALICS);}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 71 "latex2html.l"
{printf(" %s ", yytext);; return(ITALICS);}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 72 "latex2html.l"
{printf(" %s ", yytext);; return(HSPACE);}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 73 "latex2html.l"
{printf(" %s ", yytext);; return(HLINE);}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 74 "latex2html.l"
{printf(" %s ", yytext);; if(inmath == 0) return(B); else {yylval.arr = strdup(yytext); return(LETTERS);}}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 75 "latex2html.l"
{printf(" %s ", yytext);; if(inmath == 0) return(C); else {yylval.arr = strdup(yytext); return(LETTERS);}}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 76 "latex2html.l"
{printf(" %s ", yytext);; if(inmath == 0) return(H); else {yylval.arr = strdup(yytext); return(LETTERS);}}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 77 "latex2html.l"
{printf(" %s ", yytext);; if(inmath == 0) return(L); else {yylval.arr = strdup(yytext); return(LETTERS);}}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 78 "latex2html.l"
{printf(" %s ", yytext);; if(inmath == 0) return(R); else {yylval.arr = strdup(yytext); return(LETTERS);}}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 79 "latex2html.l"
{printf(" %s ", yytext);; if(inmath == 0) return(T); else {yylval.arr = strdup(yytext); return(LETTERS);}}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 80 "latex2html.l"
{printf(" %s ", yytext);; return(FRAC);}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 81 "latex2html.l"
{printf(" %s ", yytext);; return(SQRT);}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 82 "latex2html.l"
{printf(" %s ", yytext);;  if(inmath == 1){ yytext="&inf"; yylval.arr = strdup(yytext);return(GREEK);}else{ yylval.arr = strdup(yytext); return(LETTERS);}}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 83 "latex2html.l"
{printf(" %s ", yytext);;  if(inmath == 1){ yytext[0]='&'; yylval.arr = strdup(yytext);return(GREEK);}else{ yylval.arr = strdup(yytext); return(LETTERS);}}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 84 "latex2html.l"
{printf(" %s ", yytext);; if(inmath == 1) {yylval.arr = strdup(yytext); return(LETTERS);}else{yylval.arr = strdup(yytext); return(WORD);}}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 85 "latex2html.l"
{printf(" %s ", yytext);; /* if(incomment == 0) */ yylval.val = atoi(yytext); return(INTEGER);}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 87 "latex2html.l"
{printf(" %s ", yytext);; yylval.arr = strdup(yytext); if(inmath == 1) return(LETTERS); else return(WORD); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 88 "latex2html.l"
{/* printf(" %s ", yytext);;  return(WS); */}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 89 "latex2html.l"
{}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 91 "latex2html.l"
{printf(" %s",yytext);; yytext=" ";return(SWORD);}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 92 "latex2html.l"
{printf("Cannot Parse. \n");;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 93 "latex2html.l"
ECHO;
	YY_BREAK
#line 1490 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 546 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 546 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 545);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 93 "latex2html.l"


