#ifndef ERRORCONFIG_H__
#define ERRORCONFIG_H__

#define MAXSTRING 80

#define ERROR_ID_NOT_FOUND 0x0FFFFFFF
#define ERROR_ID_ALREADY_EXISTS 0x0FFFFFFE
#define ERROR_TABLE_IN_GLOBAL_SCOPE 0x0FFFFFFD
#define ERROR_MALLOC_FAILURE 0x0FFFFFFC
#define ERROR_FUNCTION_EXISTS 0x0FFFFFFB
#define ERROR_FUNCTION_NOT_DEFINED 0x0FFFFFFA
#define ERROR_FUNCTION_ALREADY_DEFINED 0x0FFFFFF9
#define ERROR_STACK_EMPTY 0x0FFFFFF8
#define ERROR_BAD_ARRAY_DIMENSION 0x0FFFFFF7

#endif //ERRORCONFIG_H__
